# Generated by Django 4.2.23 on 2025-09-09 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cycle_type', models.CharField(choices=[('daily', 'Daily Cycle'), ('yearly', 'Yearly Cycle'), ('business', 'Business Cycle'), ('health', 'Health Cycle'), ('soul', 'Soul Cycle'), ('reincarnation', 'Reincarnation Cycle')], default='daily', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CyclePeriodDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(max_length=100)),
                ('start_value', models.IntegerField(help_text='Start value (e.g., day number, hour, minute)')),
                ('end_value', models.IntegerField(help_text='End value (e.g., day number, hour, minute)')),
                ('description', models.TextField()),
                ('recommendations', models.TextField()),
                ('color', models.CharField(default='blue', max_length=20)),
                ('cycle_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_details', to='cycles.cycletemplate')),
            ],
            options={
                'ordering': ['start_value'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
