# Generated by Django 4.2.23 on 2026-05-27 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycletemplate',
            name='cycle_type',
            field=models.CharField(choices=[('daily', 'Daily Cycle'), ('yearly', 'Yearly Cycle'), ('human', 'Human Life Cycle'), ('business', 'Business Cycle'), ('health', 'Health Cycle'), ('soul', 'Soul Cycle'), ('reincarnation', 'Reincarnation Cycle')], default='daily', max_length=20),
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('mood', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Great'), (5, 'Excellent')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cycles.cycleperioddetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Journal entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
