# Generated by Django 4.2.23 on 2026-05-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_alter_cycletemplate_cycle_type_journalentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, unique=True)),
                ('definition', models.TextField()),
                ('related_cycle_type', models.CharField(blank=True, choices=[('daily', 'Daily Cycle'), ('yearly', 'Yearly Cycle'), ('human', 'Human Life Cycle'), ('business', 'Business Cycle'), ('health', 'Health Cycle'), ('soul', 'Soul Cycle'), ('reincarnation', 'Reincarnation Cycle')], max_length=20, null=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Glossary terms',
                'ordering': ['sort_order', 'term'],
            },
        ),
        migrations.AddField(
            model_name='cycleperioddetail',
            name='lesson_content',
            field=models.TextField(blank=True, help_text='Deep educational content about this period (rich text)'),
        ),
    ]
